### ISSUE TITLE
Error on snapshot

### ISSUE THREAD

**Issue by mdPlusPlus** [sirpdboy/luci-theme-opentopd#7]
OpenWrt SNAPSHOT r19160-7ea2f3d6e2 / LuCI Master git-22.058.70382-d29400e
Version: [luci-theme-opentopd_1.4.7-20211215_all.ipk](https://github.com/sirpdboy/luci-theme-opentopd/releases/download/1.4.7/luci-theme-opentopd_1.4.7-20211215_all.ipk)

`Status: 500 Internal Server Error /usr/lib/lua/luci/template.lua:97: Failed to execute template 'view'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/opentopd/header'. A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/opentopd/head..."]:22: attempt to call field 'node_childs' (a nil value) stack traceback: [string "/usr/lib/lua/luci/view/themes/opentopd/head..."]:22: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function 'render' /usr/lib/lua/luci/dispatcher.lua:696: in function 'include' [string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function 'render' /usr/lib/lua/luci/dispatcher.lua:696: in function 'include' [string "/usr/lib/lua/luci/view/view.htm"]:1: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function (tail call): ? /usr/lib/lua/luci/dispatcher.lua:986: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:479: in function `

**Comment by sirpdboy** [comment]
目前这个只支持1806版本。1907以上 不支持。
